#!/bin/bash
# Vercel Deployment Script: Injects environment variables into the static config.js file

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
  echo "ERROR: SUPABASE_URL and SUPABASE_ANON_KEY must be set in your Vercel Environment Variables."
  exit 1
fi

cat <<EOF > config.js
// AUTO-GENERATED BY build.sh DURING DEPLOYMENT
export const SUPABASE_URL = '${SUPABASE_URL}';
export const SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';

if (!SUPABASE_URL || !SUPABASE_ANON_KEY || SUPABASE_URL.startsWith('YOUR_')) {
    throw new Error('FATAL: Supabase configuration is missing. The application cannot start without valid keys.');
}
EOF

echo "Successfully generated config.js"
